### ISSUE TITLE
divide by zero

### ISSUE THREAD

**Issue by viisauksena** [christf/fastd-peer-balance#3]
super ...nice .. 

beim ersten drübersehen ist mir aufgefallen das du batctl gwl um 1 verringerst. was passiert denn wenn das null wird, oder sogar minus 1 (bspw. weil "no gateways found" - 1 = 0) 
.. 
der folgende divide by 0 is doof
```
  gwamount=$(($($BATCTL gwl -H |wc -l)-1))
  connection_average_estimate=$(( net_peer_amount / gwamount ))

```

**Comment by christf** [comment]
das ist der preis, wenn man es nicht direkt testet und den code im blindflug schreibt. ich glaub das ist momentan nur eine sehr grobe Schätzung, da kann man bestimmt noch mehr machen... die division durch 0 schau ich mir an, danke fürs merken! :)

**Comment by christf** [comment]
done.
